[package]
name = "rsdl3"
version = "0.1.0"
edition = "2021"

[features]
default = ["image"]
image = ["rsdl3-sys/image"]

[dependencies]
rsdl3-sys = { path = "../rsdl3-sys" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
